### ISSUE TITLE
Typo in function v3_ceil

### ISSUE THREAD

**Issue by jangarita** [croquet/worldcore#4]
In packages/kernel/src/Vector.js there is a typo in function [v3_ceil](https://github.com/croquet/worldcore/blob/82491c3bc64b3fe69766838ab251f0acf184aba3/packages/kernel/src/Vector.js#L265)

Should be:
```
export function v3_ceil(v) {
    return [Math.ceil(v[0]), Math.ceil(v[1]), Math.ceil(v[2])];
}
```

Instead of:
```
export function v3_ceil(v) {
    return [Math.ceil(v[0]), Math.v3_ceil(v[1]), Math.ceil(v[2])];
}
```

**Comment by Croquetx** [comment]
Thanks! Fixed here and will be in next release.
